# Deploys a mongodb instance vulnerable to CVE-2025-14847
# kube play mongodb.yaml
apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
spec:
  containers:
    - name: mongobleed-target
      image: docker.io/mongo:8.2.2
      ports:
        - containerPort: 27017
          hostPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: SuperSecret123!
        - name: MONGO_INITDB_DATABASE
          value: secretdb
      command:
        - mongod
        - --networkMessageCompressors
        - zlib
        - --bind_ip_all
      volumeMounts:
        - name: mongo-init
          mountPath: /docker-entrypoint-initdb.d/init-mongo.js
          readOnly: true
          subPath: init-mongo.js
        - name: mongo-data
          mountPath: /data/db
  volumes:
    - name: mongo-init
      hostPath:
        path: ./init
        type: Directory
    - name: mongo-data
      hostPath:
        path: ./mongodb_data
        type: DirectoryOrCreate
