# Deploys a mongodb instance vulnerable to CVE-2025-14847
# kube play mongodb.yaml
apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
spec:
  containers:
    - name: mongobleed-target
      image: docker.io/mongo:8.2.2
      ports:
        - containerPort: 27017
          hostPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: SuperSecret123!
        - name: MONGO_INITDB_DATABASE
          value: secretdb
      command:
        - mongod
        - --networkMessageCompressors
        - zlib
        - --bind_ip_all
      volumeMounts:
        - name: mongo-init
          mountPath: /docker-entrypoint-initdb.d/init-mongo.js
          readOnly: true
          subPath: init-mongo.js
        - name: mongo-data
          mountPath: /data/db
    - name: mongo-tls-proxy
      image: docker.io/nginx:1.27-alpine
      ports:
        - containerPort: 27071
          hostPort: 27071
      volumeMounts:
        - name: mongo-tls
          mountPath: /certs
      command:
        - /bin/sh
        - -c
        - |
          set -euo pipefail
          apk add --no-cache openssl 2>&1 >/dev/null
          CERT_DIR=/certs
          mkdir -p "${CERT_DIR}"
          if [ ! -f "${CERT_DIR}/server.key" ]; then
            openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
              -keyout "${CERT_DIR}/server.key" \
              -out "${CERT_DIR}/server.crt" \
              -subj "/CN=localhost" 2>&1 > /dev/null
          fi
          cat > /etc/nginx/nginx.conf <<'EOF'
          events { worker_connections 1024; }
          stream {
            log_format proxy '$remote_addr:$remote_port -> $server_addr:$server_port '
                             '$protocol $status $bytes_sent/$bytes_received $session_time';
            access_log /dev/stdout proxy;
            error_log  /dev/stderr info;
            upstream mongo_backend { server 127.0.0.1:27017; }
            server {
              listen 0.0.0.0:27071 ssl;
              proxy_pass mongo_backend;
              ssl_protocols TLSv1.2 TLSv1.3;
              ssl_certificate /certs/server.crt;
              ssl_certificate_key /certs/server.key;
            }
          }
          EOF
          exec nginx -g 'daemon off;'
  volumes:
    - name: mongo-init
      hostPath:
        path: ./init
        type: Directory
    - name: mongo-data
      hostPath:
        path: ./mongodb_data
        type: DirectoryOrCreate
    - name: mongo-tls
      emptyDir: {}
